// Autogenerated by Frugal Compiler (2.22.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING



import 'dart:async';
import 'dart:typed_data' show Uint8List;

import 'package:thrift/thrift.dart' as thrift;
import 'package:frugal/frugal.dart' as frugal;

import 'package:v1_music/v1_music.dart' as t_v1_music;


const String delimiter = '.';

/// Scopes are a Frugal extension to the IDL for declaring PubSub
/// semantics. Subscribers to this scope will be notified if they win a contest.
/// Scopes must have a prefix.
class AlbumWinnersPublisher {
  frugal.FPublisherTransport transport;
  frugal.FProtocolFactory protocolFactory;
  List<frugal.Middleware> _combinedMiddleware;
  frugal.FMethod _contestStart_fmethod;
  frugal.FMethod _timeLeft_fmethod;
  frugal.FMethod _winner_fmethod;
  AlbumWinnersPublisher(frugal.FScopeProvider provider, [List<frugal.Middleware> middleware]) {
    transport = provider.publisherTransportFactory.getTransport();
    protocolFactory = provider.protocolFactory;
    _combinedMiddleware = middleware ?? [];
    _combinedMiddleware.addAll(provider.middleware);
  }

  Future open() {
    return transport.open();
  }

  Future close() {
    return transport.close();
  }

  Future publishContestStart(frugal.FContext ctx, List<t_v1_music.Album> req) {
    if (_contestStart_fmethod == null) {
      _contestStart_fmethod = new frugal.FMethod(this._publishContestStart, 'AlbumWinners', 'publishContestStart', _combinedMiddleware);
    }
    return _contestStart_fmethod([ctx, req]);
  }

  Future _publishContestStart(frugal.FContext ctx, List<t_v1_music.Album> req) async {
    var op = "ContestStart";
    var prefix = "v1.music.";
    var topic = "${prefix}AlbumWinners${delimiter}${op}";
    var memoryBuffer = new frugal.TMemoryOutputBuffer(transport.publishSizeLimit);
    var oprot = protocolFactory.getProtocol(memoryBuffer);
    var msg = new thrift.TMessage(op, thrift.TMessageType.CALL, 0);
    oprot.writeRequestHeader(ctx);
    oprot.writeMessageBegin(msg);
    oprot.writeListBegin(new thrift.TList(thrift.TType.STRUCT, req.length));
    for(var elem4 in req) {
      elem4.write(oprot);
    }
    oprot.writeListEnd();
    oprot.writeMessageEnd();
    await transport.publish(topic, memoryBuffer.writeBytes);
  }


  Future publishTimeLeft(frugal.FContext ctx, double req) {
    if (_timeLeft_fmethod == null) {
      _timeLeft_fmethod = new frugal.FMethod(this._publishTimeLeft, 'AlbumWinners', 'publishTimeLeft', _combinedMiddleware);
    }
    return _timeLeft_fmethod([ctx, req]);
  }

  Future _publishTimeLeft(frugal.FContext ctx, double req) async {
    var op = "TimeLeft";
    var prefix = "v1.music.";
    var topic = "${prefix}AlbumWinners${delimiter}${op}";
    var memoryBuffer = new frugal.TMemoryOutputBuffer(transport.publishSizeLimit);
    var oprot = protocolFactory.getProtocol(memoryBuffer);
    var msg = new thrift.TMessage(op, thrift.TMessageType.CALL, 0);
    oprot.writeRequestHeader(ctx);
    oprot.writeMessageBegin(msg);
    oprot.writeDouble(req);
    oprot.writeMessageEnd();
    await transport.publish(topic, memoryBuffer.writeBytes);
  }


  Future publishWinner(frugal.FContext ctx, t_v1_music.Album req) {
    if (_winner_fmethod == null) {
      _winner_fmethod = new frugal.FMethod(this._publishWinner, 'AlbumWinners', 'publishWinner', _combinedMiddleware);
    }
    return _winner_fmethod([ctx, req]);
  }

  Future _publishWinner(frugal.FContext ctx, t_v1_music.Album req) async {
    var op = "Winner";
    var prefix = "v1.music.";
    var topic = "${prefix}AlbumWinners${delimiter}${op}";
    var memoryBuffer = new frugal.TMemoryOutputBuffer(transport.publishSizeLimit);
    var oprot = protocolFactory.getProtocol(memoryBuffer);
    var msg = new thrift.TMessage(op, thrift.TMessageType.CALL, 0);
    oprot.writeRequestHeader(ctx);
    oprot.writeMessageBegin(msg);
    req.write(oprot);
    oprot.writeMessageEnd();
    await transport.publish(topic, memoryBuffer.writeBytes);
  }
}


/// Scopes are a Frugal extension to the IDL for declaring PubSub
/// semantics. Subscribers to this scope will be notified if they win a contest.
/// Scopes must have a prefix.
class AlbumWinnersSubscriber {
  final frugal.FScopeProvider provider;
  final List<frugal.Middleware> _middleware;

  AlbumWinnersSubscriber(this.provider, [List<frugal.Middleware> middleware])
      : this._middleware = middleware ?? [] {
    this._middleware.addAll(provider.middleware);
}

  Future<frugal.FSubscription> subscribeContestStart(dynamic onlist(frugal.FContext ctx, List<t_v1_music.Album> req)) async {
    var op = "ContestStart";
    var prefix = "v1.music.";
    var topic = "${prefix}AlbumWinners${delimiter}${op}";
    var transport = provider.subscriberTransportFactory.getTransport();
    await transport.subscribe(topic, _recvContestStart(op, provider.protocolFactory, onlist));
    return new frugal.FSubscription(topic, transport);
  }

  frugal.FAsyncCallback _recvContestStart(String op, frugal.FProtocolFactory protocolFactory, dynamic onlist(frugal.FContext ctx, List<t_v1_music.Album> req)) {
    callbackContestStart(thrift.TTransport transport) {
      var iprot = protocolFactory.getProtocol(transport);
      var ctx = iprot.readRequestHeader();
      var tMsg = iprot.readMessageBegin();
      if (tMsg.name != op) {
        thrift.TProtocolUtil.skip(iprot, thrift.TType.STRUCT);
        iprot.readMessageEnd();
        throw new thrift.TApplicationError(
        frugal.FrugalTApplicationErrorType.UNKNOWN_METHOD, tMsg.name);
      }
      thrift.TList elem5 = iprot.readListBegin();
      List<t_v1_music.Album> req = new List<t_v1_music.Album>();
      for(int elem7 = 0; elem7 < elem5.length; ++elem7) {
        t_v1_music.Album elem6 = new t_v1_music.Album();
        elem6.read(iprot);
        req.add(elem6);
      }
      iprot.readListEnd();
      iprot.readMessageEnd();
      frugal.composeMiddleware(onlist, _middleware)('AlbumWinners', 'subscribelist', [ctx, req]);
    }
    return callbackContestStart;
  }


  Future<frugal.FSubscription> subscribeTimeLeft(dynamic onMinutes(frugal.FContext ctx, double req)) async {
    var op = "TimeLeft";
    var prefix = "v1.music.";
    var topic = "${prefix}AlbumWinners${delimiter}${op}";
    var transport = provider.subscriberTransportFactory.getTransport();
    await transport.subscribe(topic, _recvTimeLeft(op, provider.protocolFactory, onMinutes));
    return new frugal.FSubscription(topic, transport);
  }

  frugal.FAsyncCallback _recvTimeLeft(String op, frugal.FProtocolFactory protocolFactory, dynamic onMinutes(frugal.FContext ctx, double req)) {
    callbackTimeLeft(thrift.TTransport transport) {
      var iprot = protocolFactory.getProtocol(transport);
      var ctx = iprot.readRequestHeader();
      var tMsg = iprot.readMessageBegin();
      if (tMsg.name != op) {
        thrift.TProtocolUtil.skip(iprot, thrift.TType.STRUCT);
        iprot.readMessageEnd();
        throw new thrift.TApplicationError(
        frugal.FrugalTApplicationErrorType.UNKNOWN_METHOD, tMsg.name);
      }
      double req = iprot.readDouble();
      iprot.readMessageEnd();
      frugal.composeMiddleware(onMinutes, _middleware)('AlbumWinners', 'subscribeMinutes', [ctx, req]);
    }
    return callbackTimeLeft;
  }


  Future<frugal.FSubscription> subscribeWinner(dynamic onAlbum(frugal.FContext ctx, t_v1_music.Album req)) async {
    var op = "Winner";
    var prefix = "v1.music.";
    var topic = "${prefix}AlbumWinners${delimiter}${op}";
    var transport = provider.subscriberTransportFactory.getTransport();
    await transport.subscribe(topic, _recvWinner(op, provider.protocolFactory, onAlbum));
    return new frugal.FSubscription(topic, transport);
  }

  frugal.FAsyncCallback _recvWinner(String op, frugal.FProtocolFactory protocolFactory, dynamic onAlbum(frugal.FContext ctx, t_v1_music.Album req)) {
    callbackWinner(thrift.TTransport transport) {
      var iprot = protocolFactory.getProtocol(transport);
      var ctx = iprot.readRequestHeader();
      var tMsg = iprot.readMessageBegin();
      if (tMsg.name != op) {
        thrift.TProtocolUtil.skip(iprot, thrift.TType.STRUCT);
        iprot.readMessageEnd();
        throw new thrift.TApplicationError(
        frugal.FrugalTApplicationErrorType.UNKNOWN_METHOD, tMsg.name);
      }
      t_v1_music.Album req = new t_v1_music.Album();
      req.read(iprot);
      iprot.readMessageEnd();
      frugal.composeMiddleware(onAlbum, _middleware)('AlbumWinners', 'subscribeAlbum', [ctx, req]);
    }
    return callbackWinner;
  }
}

